[build]
    functions="functions"
    command = "echo 'this is only here so that netlify deploys functions within folders'"

[[redirects]]
    to="/.netlify/functions/index"
    from="/*"
    status=200
